### ISSUE TITLE
I have a question.

### ISSUE THREAD

**Issue by heieirk** [CactusHamster/EmojiLib#1]
How did you create macadamia-web.herokuapp.com? I would like to see your repository.

**Comment by CactusHamster** [comment]
@heieirk GitHub issues are probably a bad place for questions like this. If you'd like I can use discord? My tag is `bírb#8407`.
Also, I don't have a repository for Macadamia ;3

**Comment by habataku** [comment]
Sorry for the late reply. I found a code similar to https://macadamia-web.herokuapp.com/ and thought you were the creator of this site. I am also sorry that the question was an issue

**Comment by CactusHamster** [comment]
If you have a question, please use anything other than permanent issues on my repositories.
